#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Hash of the last commit
PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
CURRENT_COMMIT=$(git rev-parse HEAD)

# https://stackoverflow.com/a/41553472/5631003
for DIR in ./libs/*/ ; do (

# This is necessary to avoid loops when `yarn version` commits
# as --no-commit-hooks does not work
DIR_SRC="${DIR}src/"

# Detect changes in the last commit
CHANGED=false
# If exit code is 1 then changes have been made
git diff "$PREVIOUS_COMMIT" "$CURRENT_COMMIT" --quiet -- "$DIR_SRC" || CHANGED=true

if [ $CHANGED = true ] ; then
  yarn --cwd "$DIR" version --patch --no-commit-hooks
fi

); done
