name: Publish

on:
  pull_request:
    branches:
      - master_
  push:
    branches:
      - master_

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish all packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0 # Same as .nvmrc
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint js-acl
        run: yarn lint js-acl
      - name: Test js-acl
        run: yarn test js-acl
      - name: Build js-acl
        run: yarn build js-acl
      - name: Publish js-acl
        run: cd dist/libs/js-acl && npm publish --access public
        continue-on-error: true

      - name: Lint js-helpers
        run: yarn lint js-helpers
      - name: Test js-helpers
        run: yarn test js-helpers
      - name: Build js-helpers
        run: yarn build js-helpers
      - name: Publish js-helpers
        run: cd dist/libs/js-helpers && npm publish --access public
        continue-on-error: true

      - name: Lint ng-dynamic-router
        run: yarn lint ng-dynamic-router
      - name: Test ng-dynamic-router
        run: yarn test ng-dynamic-router
      - name: Build ng-dynamic-router
        run: yarn build ng-dynamic-router
      - name: Publish ng-dynamic-router
        run: cd dist/libs/ng-dynamic-router && npm publish --access public
        continue-on-error: true

      - name: Lint ng-helpers
        run: yarn lint ng-helpers
      - name: Test ng-helpers
        run: yarn test ng-helpers
      - name: Build ng-helpers
        run: yarn build ng-helpers
      - name: Publish ng-helpers
        run: cd dist/libs/ng-helpers && npm publish --access public
        continue-on-error: true

      - name: Lint ng-suspense
        run: yarn lint ng-suspense
      - name: Test ng-suspense
        run: yarn test ng-suspense
      - name: Build ng-suspense
        run: yarn build ng-suspense
      - name: Publish ng-suspense
        run: cd dist/libs/ng-suspense && npm publish --access public
        continue-on-error: true

      - name: Lint ng-flex
        run: yarn lint ng-flex
      - name: Test ng-flex
        run: yarn test ng-flex
      - name: Build ng-flex
        run: yarn build ng-flex
      - name: Publish ng-flex
        run: cd dist/libs/ng-flex && npm publish --access public
        continue-on-error: true

      - name: Lint ng-material-components-web
        run: yarn lint ng-material-components-web
      - name: Test ng-material-components-web
        run: yarn test ng-material-components-web
      - name: Build ng-material-components-web
        run: yarn build ng-material-components-web
      - name: Publish ng-material-components-web
        run: cd dist/libs/ng-material-components-web && npm publish --access public
        continue-on-error: true

      - name: Lint express-http-error
        run: yarn lint express-http-error
      - name: Test express-http-error
        run: yarn test express-http-error
      - name: Build express-http-error
        run: yarn build express-http-error
      - name: Publish express-http-error
        run: cd dist/libs/express-http-error && npm publish --access public
        continue-on-error: true

      - name: Lint express-params
        run: yarn lint express-params
      - name: Test express-params
        run: yarn test express-params
      - name: Build express-params
        run: yarn build express-params
      - name: Publish express-params
        run: cd dist/libs/express-params && npm publish --access public
        continue-on-error: true

      - name: Lint express-helpers
        run: yarn lint express-helpers
      - name: Test express-helpers
        run: yarn test express-helpers
      - name: Build express-helpers
        run: yarn build express-helpers
      - name: Publish express-helpers
        run: cd dist/libs/express-helpers && npm publish --access public
        continue-on-error: true

      - name: Lint express-mysql
        run: yarn lint express-mysql
      - name: Test express-mysql
        run: yarn test express-mysql
      - name: Build express-mysql
        run: yarn build express-mysql
      - name: Publish express-mysql
        run: cd dist/libs/express-mysql && npm publish --access public
        continue-on-error: true

      - name: Lint ng-router-history
        run: yarn lint ng-router-history
      - name: Test ng-router-history
        run: yarn test ng-router-history
      - name: Build ng-router-history
        run: yarn build ng-router-history
      - name: Publish ng-router-history
        run: cd dist/libs/ng-router-history && npm publish --access public
        continue-on-error: true
