name: Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test js-acl
        run: yarn test js-acl
      - name: Build js-acl
        run: yarn build js-acl
      - name: Publish js-acl
        run: cd dist/libs/js-acl && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Test js-helpers
        run: yarn test js-helpers
      - name: Build js-helpers
        run: yarn build js-helpers
      - name: Publish js-helpers
        run: cd dist/libs/js-helpers && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Test ng-dynamic-router
        run: yarn test ng-dynamic-router
      - name: Build ng-dynamic-router
        run: yarn build ng-dynamic-router
      - name: Publish ng-dynamic-router
        run: cd dist/libs/ng-dynamic-router && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Test ng-helpers
        run: yarn test ng-helpers
      - name: Build ng-helpers
        run: yarn build ng-helpers
      - name: Publish ng-helpers
        run: cd dist/libs/ng-helpers && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
